---
title: "Organiser Essentials"
subtitle: "Productivity"
author: "Hamish Gamble"
affiliation: "National Research Centre - AMWU"
execute: 
  echo: false
  warning: false
  message: false
brand: _extensions/amwu-nrc/amwu-brand/brand.yml
format: 
  revealjs: 
    auto-play-media: true
    fig-format: svg
    incremental: true
  pptx: 
    incremental: false 
    slide-level: 2
    fig-format: svg
    reference-doc: template.pptx
editor: visual
---

## Organiser Essentials

::: notes
This is the first session in the NRC Legal, Political and Economic Education Series which we are developing. These sessions are designed to:

-   help build a culture of mindful militancy
-   have a shared understanding (as a union) on legal, political, and economic issues
-   provide consistency in training across delegates and organisers, to help with coaching and mentoring of delegates following DU4 and more broadly around knowledge and skill building.
-   provide some useful talking points in recruitment and organising conversations.
-   What comes next will be influenced by what you think you need/what you think will be useful
:::

-   These sessions are designed to help build a culture of mindful militancy.

-   Tell us what you need.

## Talking about Productivity

::: notes
The most important thing with productivity - who benefits?
:::

-   Why do you need to understand productivity?

-   What is productivity, and what is it not?

-   What factors affect trends in productivity?

-   Talking about productivity in the workplace

{{< include sections/_section-02b-productivity.qmd >}}

## Productivity and Management

::: notes
The things which primarily determine productivity are things in which the worker does not have much control.

Physical capital, technology and innovation, and management practices are all decisions of the managerial class.

Health comes down to many factors, including work health and safety, psychosocial hazards, but also being able to get sufficient rest between shifts, and sufficient time off for leisure. Ultimately this comes down to wages. If wages aren't high enough, workers will look to overtime, taking extra shifts, and minimising leisure time - because they need to to survive.

For skills there is also the issue of wages. Workforce development should be the role of management, not the role of the worker. Individual workers should not feel they have to take leave or paid training to support the boss generating more profit. Also the labour market in Australia is highly concentrated, and workers are underpaid relative to their skills - further disincentivising training. What's the point in paying for your own training if it won't get you a higher pay packet? Again - this is the individual improving productivity just to benefit the boss.
:::

Productivity is primarily determined by:

-   Physical capital like tools, and machines

-   Technology and innovation

-   Management of resources

-   The health and skills of workers

## Productivity and Public Policy

::: notes
We have a lot of levers at our disposal to improve productivity. Unfortunately (for the boss) most of these require them to either take a hit to their profit, or reinvest some of that profit into their business!
:::

What policy levers can be used to increase productivity?

-   Worker health

-   Skills

-   Investment

-   Environmental regulation

-   Managerial practices

# Productivity in the Workplace

::: notes
Talking points that you might find useful in starting a conversation in the workplace
:::

## Productivity in the Workplace

::: notes
This is an almost direct quote from Australian Chamber of Commerce and Industry chief executive Andrew McKellar in the AFR. https://www.afr.com/policy/economy/rba-says-australians-will-have-to-accept-lower-wages-growth-20251015-p5n2ms
:::

They say:

> Unions need to moderate their wage claims, and offer measures to improve labour productivity.

-   Who makes decisions that impact on labour productivity? Workers or Bosses?

## Productivity in the Workplace - Health

-   Are workers earning enough to live without constant stress?
-   Are workplace health and safety risks properly addressed?
-   Do workers have sufficient time to rest and recover?

## Productivity in the Workplace - Skills

-   Are workers given opportunities to develop their skills and advance their careers?

-   Does the company cover training costs? Or offer time off?

-   Are there incentives to train?

## Productivity in the Workplace - Investment

-   Is the company investing in physical capital and research?

-   Are workers provided with the tools and materials they need to be productive?

## Productivity in the Workplace - Management

-   Is time wasted on non-value adding tasks?

-   Can workers raise and resolve issues with management?

-   Are workers deployed effectively?

## Productivity in the Workplace

-   Productivity in the workplace is shaped by the choices companies make

-   Companies can be profitable without being productive.

-   Workers need to be able to discuss productivity openly so they can challenge misleading claims.

## The NRC is Here to Help

-   Please reach out if you need any help

-   Contact us on nrc\@amwu.org.au
